require("dotenv").config();

const {
  PORT,
  DB_HOST,
  DB_PORT,
  DB_USER,
  DB_PASSWORD,
  DB_DATABASE,
  HASH_SALT_ROUNDS,
  AI_API_URL,
  KEYCLOAK_SERVER_URL,
  KEYCLOAK_REALM,
  KEYCLOAK_CLIENT_ID,
  KEYCLOAK_CLIENT_SECRET,
  YOUR_USER_POOL_ID,
  YOUR_APP_CLIENT_ID,
} = process.env;
module.exports = {
  PORT,
  DB_HOST,
  DB_PORT,
  DB_USER,
  DB_PASSWORD,
  DB_DATABASE,
  HASH_SALT_ROUNDS,
  AI_API_URL,
  KEYCLOAK_SERVER_URL,
  KEYCLOAK_REALM,
  KEYCLOAK_CLIENT_ID,
  KEYCLOAK_CLIENT_SECRET,
  YOUR_USER_POOL_ID,
  YOUR_APP_CLIENT_ID,
};